export const catalogs = [
  { id: 0, image: "/images/products/Аризона.jpg", name: "Аризона", desc: "" },
  { id: 1, image: "/images/products/Ясень Бородино.jpg", name: "Ясень Бородино", desc: "" },
  { id: 2, image: "/images/products/астана пайн.jpg", name: "астана пайн", desc: "" },
  { id: 3, image: "/images/products/Баунти.jpg", name: "Баунти", desc: "" },
  { id: 4, image: "/images/products/Бахия палисандр и австралия.jpg", name: "Бахия палисандр и австралия", desc: "" },
  { id: 5, image: "/images/products/береза одесса, липа вегас.jpg", name: "береза одесса, липа вегас", desc: "" },
  { id: 6, image: "/images/products/Бонито (мрамор).jpg", name: "Бонито (мрамор)", desc: "" },
  { id: 7, image: "/images/products/Белая линия.jpg", name: "Белая линия", desc: "" },
  { id: 8, image: "/images/products/Белый лес.jpg", name: "Белый лес", desc: "" },
  { id: 9, image: "/images/products/береза одесса, липа вегас.jpg", name: "береза одесса, липа вегас", desc: "" },
  { id: 10, image: "/images/products/Бук Бавария.jpg", name: "Бук Бавария", desc: "" },
  { id: 11, image: "/images/products/Венге.jpg", name: "Венге", desc: "" },
  { id: 12, image: "/images/products/Вишня.jpg", name: "Вишня", desc: "" },
  { id: 13, image: "/images/products/Вяз Китами 02.jpg", name: "Вяз Китами 02", desc: "" },
  { id: 14, image: "/images/products/Гиккори Джексон.jpg", name: "Гиккори Джексон", desc: "" },
  { id: 15, image: "/images/products/Гикори Джексон средний.jpg", name: "Гикори Джексон средний", desc: "" },
  { id: 16, image: "/images/products/дуб белый.jpg", name: "дуб белый", desc: "" },
];
